#!/bin/sh -eu
#
# As of 0.13, xmonad --recompile will look for a custom build script.
# https://github.com/xmonad/xmonad/issues/102

EXE_NAME=xmonad-x86_64-linux
OUTPUT=$1

stack install
cp -uf $(stack exec which $EXE_NAME) $OUTPUT
